In [106]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
matplotlib.style.use('ggplot')
# use the code below to make sure plot is shown in Notebook
%matplotlib inline 

In [321]:
Train_cleaned = pd.read_csv('F:\MSBAPM\Travellers\Train_final2.csv')

In [322]:
Train_cleaned.cancel.value_counts()

0    5706
1    1843
Name: cancel, dtype: int64

In [323]:
Train_cleaned.columns

Index(['id', 'tenure', 'claim.ind', 'n.adults', 'n.children', 'ni.gender',
       'ni.marital.status', 'premium', 'sales.channel', 'coverage.type',
       'dwelling.type', 'len.at.res_withoutotliers', 'credit', 'house.color',
       'ni.age_withoutoutliers', 'year', 'combo1', 'zip.code', 'cancel',
       'Premium range', 'Combo2_final', 'zip.code.1'],
      dtype='object')

In [369]:
#define x and y parameters
feature_cols = [ 'tenure', 'claim.ind', 'n.adults', 'n.children', 'ni.marital.status', 'Premium range',  'sales.channel', 
        'len.at.res_withoutotliers', 'credit', 'ni.age_withoutoutliers', 'zip.code.1']

In [370]:
# X is a matrix, hence we use [] to access the features we want in feature_cols
X1 = Train_cleaned[feature_cols]

In [371]:
X1.head()

tenure  claim.ind  n.adults  n.children  ni.marital.status  Premium range  \
0      12          0         4           2                  1            800   
1      18          0         2           0                  1            800   
2       4          0         2           0                  0           1000   
3      16          0         1           0                  1           1000   
4      14          0         3           3                  1            800   

   sales.channel  len.at.res_withoutotliers  credit  ni.age_withoutoutliers  \
0              1                       13.0       1                    47.0   
1              1                       15.0       1                    47.0   
2              2                       10.0       2                    30.0   
3              1                       22.0       1                    38.0   
4              2                       18.0       3                    49.0   

   zip.code.1  
0         800  
1         500  
2         500  
3         800  
4         500

NameError: name 'Combo2_final' is not defined

In [372]:
# y is a vector, hence we use dot to access 'label'
y1 = Train_cleaned.cancel

# Logistic Model

In [328]:
# split X and y into training and testing sets
from sklearn.cross_validation import train_test_split
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, random_state=0)

In [329]:
# train a logistic regression model on the training set
from sklearn.linear_model import LogisticRegression

# instantiate model
logreg = LogisticRegression()

# fit model
model = logreg.fit(X1_train, y1_train)

In [330]:
# make class predictions for the testing set
y1_pred_class = model.predict(X1_test)


In [252]:
# print the first 25 true and predicted responses
#print('True:', y_test.values[0:100])
#print('False:', y_pred_class[0:1000])
#print('False:', y_train.values[0:100])
y1_pred_class

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [295]:
np.unique(y1_pred_class)

array([0, 1], dtype=int64)

In [331]:
# calculate accuracy
from sklearn import metrics
print(metrics.accuracy_score(y1_test, y1_pred_class))

0.775423728814


In [332]:
from sklearn.metrics import roc_auc_score

In [333]:
#sorting

r = model.predict_proba(X1_test)
r
r1 = sorted(r[:,1], reverse = True)

In [334]:
r

array([[ 0.88057712,  0.11942288],
       [ 0.92937307,  0.07062693],
       [ 0.88148609,  0.11851391],
       ..., 
       [ 0.82556042,  0.17443958],
       [ 0.90465144,  0.09534856],
       [ 0.90101764,  0.09898236]])

In [335]:
#roc_auc_score(y1_test,r[:,1])
roc_auc_score(y1_test,r1)

0.49692145920796332

In [337]:
r = model.predict_proba(X1_test)
r
roc_auc_score(y1_test,r[:,1])

0.6862207679662512

# Random Forest Classifier

In [338]:
from sklearn.ensemble import RandomForestClassifier
obj = RandomForestClassifier()
obj.fit(X1_train, y1_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [339]:
#roc_auc_score(y,obj[:,1])
result1 = obj.predict_proba(X1_test)
result1

array([[ 1. ,  0. ],
       [ 1. ,  0. ],
       [ 0.9,  0.1],
       ..., 
       [ 0.8,  0.2],
       [ 0.9,  0.1],
       [ 0.9,  0.1]])

In [340]:
r1 = sorted(result1[:,1], reverse = True)
roc_auc_score(y1_test,r1)

0.49795416899770739

In [341]:
roc_auc_score(y1_test,result1[:,1])

0.64520228731898199

# Test Data

In [354]:
Train_test = pd.read_csv('F:\MSBAPM\Travellers\Test_final.csv')

In [356]:
Train_test.columns

Index(['id', 'tenure', 'claim.ind', 'n.adults', 'n.children', 'ni.gender',
       'ni.marital.status', 'premium', 'sales.channel', 'coverage.type',
       'dwelling.type', 'len.at.res', 'credit', 'house.color', 'ni.age',
       'year', 'zip.code', 'cancel', 'Premium Range', 'combo2', 'combo1'],
      dtype='object')

In [373]:
Train_test.head()

id  tenure  claim.ind  n.adults  n.children  ni.gender  \
0  7583       5          0         1           3          1   
1  7584      15          1         1           4          1   
2  7585       1          1         3           2          0   
3  7586      12          0         4           0          0   
4  7587      11          0         1           9          1   

   ni.marital.status  premium  sales.channel coverage.type  ...   len.at.res  \
0                  1   913.62              1             C  ...         18.0   
1                  1  1018.43              2             A  ...         15.0   
2                  1   928.42              1             B  ...         13.0   
3                  0   877.65              1             B  ...         19.0   
4                  1   947.28              1             A  ...         18.0   

   credit  house.color ni.age  year  zip.code  cancel  Premium Range   combo2  \
0       2         blue     35  2017       850       1            800   101800   
1       2        white     59  2017       980       1           1000  1111000   
2       2         blue     27  2017       150       1            800    11800   
3       1         blue     35  2017       150       1            800      800   
4       1          red     34  2017       150       1            800   101800   

  combo1  
0     36  
1      5  
2     27  
3     27  
4      3  

[5 rows x 21 columns]

In [374]:
#define x and y parameters
feature_cols = [ 'tenure', 'claim.ind', 'n.adults', 'n.children', 'ni.marital.status', 'premium',  'sales.channel', 
        'len.at.res', 'credit', 'ni.age', 'zip.code']

In [375]:
X2 = Train_test[feature_cols]

In [376]:
X2.head()

tenure  claim.ind  n.adults  n.children  ni.marital.status  premium  \
0       5          0         1           3                  1   913.62   
1      15          1         1           4                  1  1018.43   
2       1          1         3           2                  1   928.42   
3      12          0         4           0                  0   877.65   
4      11          0         1           9                  1   947.28   

   sales.channel  len.at.res  credit  ni.age  zip.code  
0              1        18.0       2      35       850  
1              2        15.0       2      59       980  
2              1        13.0       2      27       150  
3              1        19.0       1      35       150  
4              1        18.0       1      34       150

In [397]:
# make class predictions for the testing set
y2 = gradient.predict(X2)
y2

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [222]:
y2[0:50]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0], dtype=int64)

In [1]:
r1 = gradient.predict_proba(X2)
r1[:,1]

NameError: name 'gradient' is not defined

In [399]:
Train_test['output'] = r1[:,1]

In [400]:
Train_test.head()

id  tenure  claim.ind  n.adults  n.children  ni.gender  \
0  7583       5          0         1           3          1   
1  7584      15          1         1           4          1   
2  7585       1          1         3           2          0   
3  7586      12          0         4           0          0   
4  7587      11          0         1           9          1   

   ni.marital.status  premium  sales.channel coverage.type    ...    credit  \
0                  1   913.62              1             C    ...         2   
1                  1  1018.43              2             A    ...         2   
2                  1   928.42              1             B    ...         2   
3                  0   877.65              1             B    ...         1   
4                  1   947.28              1             A    ...         1   

   house.color  ni.age  year  zip.code  cancel  Premium Range   combo2  \
0         blue      35  2017       850       1            800   101800   
1        white      59  2017       980       1           1000  1111000   
2         blue      27  2017       150       1            800    11800   
3         blue      35  2017       150       1            800      800   
4          red      34  2017       150       1            800   101800   

   combo1    output  
0      36  0.190027  
1       5  0.464289  
2      27  0.127449  
3      27  0.092921  
4       3  0.167470  

[5 rows x 22 columns]

In [401]:
Train_test.to_csv('F:\MSBAPM\Travellers\Test_Final_ver3.0.csv')

In [1]:
roc_auc_score(y1_test,r1[:,1])

NameError: name 'roc_auc_score' is not defined

In [225]:
Train_Final = Train_test

In [227]:
Train_Final.head()

id  tenure  claim.ind  n.adults  n.children ni.gender  Gender_numeric  \
0  7583       5          0         1           3         F               0   
1  7584      15          1         1           4         F               0   
2  7585       1          1         3           2         M               1   
3  7586      12          0         4           0         M               1   
4  7587      11          0         1           9         F               0   

   ni.marital.status      premium sales.channel  Sales_numerical  \
0                  1   913.623201        Broker                2   
1                  1  1018.426114         Phone                1   
2                  1   928.418533        Broker                2   
3                  0   877.649917        Broker                2   
4                  1   947.281913        Broker                2   

  coverage.type dwelling.type  len.at.res  credit  Credit_numerical  \
0             C        Tenant        18.0  medium                 1   
1             A         House        15.0  medium                 1   
2             B         Condo        13.0  medium                 1   
3             B         Condo        19.0    high                 2   
4             A         Condo        18.0    high                 2   

  house.color  ni.age  year  zip.code  
0        blue    35.0  2017     85066  
1       white    59.0  2017     98013  
2        blue    27.0  2017     15049  
3        blue    35.0  2017     15026  
4         red    34.0  2017     15025

In [235]:
output = pd.Series(y2)

In [239]:
Train_Final['output'] = y2

In [240]:
Train_Final.head()

id  tenure  claim.ind  n.adults  n.children ni.gender  Gender_numeric  \
0  7583       5          0         1           3         F               0   
1  7584      15          1         1           4         F               0   
2  7585       1          1         3           2         M               1   
3  7586      12          0         4           0         M               1   
4  7587      11          0         1           9         F               0   

   ni.marital.status      premium sales.channel   ...    dwelling.type  \
0                  1   913.623201        Broker   ...           Tenant   
1                  1  1018.426114         Phone   ...            House   
2                  1   928.418533        Broker   ...            Condo   
3                  0   877.649917        Broker   ...            Condo   
4                  1   947.281913        Broker   ...            Condo   

  len.at.res  credit  Credit_numerical house.color  ni.age  year  zip.code  \
0       18.0  medium                 1        blue    35.0  2017     85066   
1       15.0  medium                 1       white    59.0  2017     98013   
2       13.0  medium                 1        blue    27.0  2017     15049   
3       19.0    high                 2        blue    35.0  2017     15026   
4       18.0    high                 2         red    34.0  2017     15025   

   Output  output  
0       0       0  
1       0       0  
2       0       0  
3       0       0  
4       0       0  

[5 rows x 22 columns]

In [242]:
type(output)

pandas.core.series.Series

In [250]:
Train_Final.output.value_counts()

0    2250
1     131
Name: output, dtype: int64

In [253]:
Train_Final = Train_Final.drop(['Output'],axis = 1)

In [254]:
Train_Final.head()

id  tenure  claim.ind  n.adults  n.children ni.gender  Gender_numeric  \
0  7583       5          0         1           3         F               0   
1  7584      15          1         1           4         F               0   
2  7585       1          1         3           2         M               1   
3  7586      12          0         4           0         M               1   
4  7587      11          0         1           9         F               0   

   ni.marital.status      premium sales.channel   ...    coverage.type  \
0                  1   913.623201        Broker   ...                C   
1                  1  1018.426114         Phone   ...                A   
2                  1   928.418533        Broker   ...                B   
3                  0   877.649917        Broker   ...                B   
4                  1   947.281913        Broker   ...                A   

  dwelling.type len.at.res  credit Credit_numerical  house.color ni.age  year  \
0        Tenant       18.0  medium                1         blue   35.0  2017   
1         House       15.0  medium                1        white   59.0  2017   
2         Condo       13.0  medium                1         blue   27.0  2017   
3         Condo       19.0    high                2         blue   35.0  2017   
4         Condo       18.0    high                2          red   34.0  2017   

   zip.code  output  
0     85066       0  
1     98013       0  
2     15049       0  
3     15026       0  
4     15025       0  

[5 rows x 21 columns]

In [255]:
Train_Final.to_csv('F:\MSBAPM\Travellers\Train_Final.csv')

# Decision Tree Model

In [95]:
#Import Library
from sklearn import tree
from sklearn.metrics import roc_auc_score

In [97]:
# split X and y into training and testing sets
from sklearn.cross_validation import train_test_split
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size = 0.3,random_state=0)

In [81]:
# Create tree object 
decision = tree.DecisionTreeClassifier() 
# for classification, here you can change the algorithm as gini or entropy (information gain) by default it is gini  
# model = tree.DecisionTreeRegressor() for regression
decision

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [82]:
# Train the model using the training sets and check score
decision.fit(X1_train, y1_train)
decision.score(X1_train, y1_train)

1.0

In [83]:
#Predict Output
y_predict= decision.predict(X1_test)

In [84]:
from sklearn.metrics import accuracy_score
accuracy_score(y1_test, y_predict)

0.66701846965699207

In [86]:
#roc_auc_score(y,obj[:,1])
result = decision.predict_proba(X1_test)
result

array([[ 1.,  0.],
       [ 1.,  0.],
       [ 0.,  1.],
       ..., 
       [ 0.,  1.],
       [ 1.,  0.],
       [ 0.,  1.]])

In [87]:
roc_auc_score(y1_test,result[:,1])

0.55037786995101912

In [88]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix

pd.DataFrame(
    confusion_matrix(y1_test, y_predict),
    columns=['Predicted 0', 'Predicted 1'],
    index=['True 0', 'True 1']
)

Predicted 0  Predicted 1
True 0         1115          319
True 1          312          149

# GBM

In [389]:
#Import Library
from sklearn import tree
from sklearn.metrics import roc_auc_score
from sklearn.ensemble import GradientBoostingClassifier

In [390]:
# split X and y into training and testing sets
from sklearn.cross_validation import train_test_split
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, random_state=0)

In [391]:
gradient = GradientBoostingClassifier()
gradient

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_split=1e-07, min_samples_leaf=1,
              min_samples_split=2, min_weight_fraction_leaf=0.0,
              n_estimators=100, presort='auto', random_state=None,
              subsample=1.0, verbose=0, warm_start=False)

In [392]:
gradient.fit(X1_train, y1_train)
gradient.score(X1_train, y1_train)

0.78625684508037452

In [395]:
#roc_auc_score(y,obj[:,1])
result = gradient.predict_proba(X1_test)
result

array([[ 0.9315239 ,  0.0684761 ],
       [ 0.96029518,  0.03970482],
       [ 0.81269331,  0.18730669],
       ..., 
       [ 0.79143407,  0.20856593],
       [ 0.88289949,  0.11710051],
       [ 0.88816545,  0.11183455]])

In [349]:
r1 = sorted(result[:,1], reverse = True)
r1

[0.89922201423975867,
 0.87332707899948669,
 0.82080501602391065,
 0.80625365189143272,
 0.77866647599629668,
 0.77663723891451153,
 0.77333593704345971,
 0.76444909396239025,
 0.75490617786698389,
 0.75004836261793639,
 0.74429420508429867,
 0.74356586614866205,
 0.72365115242478895,
 0.69628948345374897,
 0.68776923595126682,
 0.68454595945745245,
 0.66593980192413516,
 0.66415325637373235,
 0.66308372093075463,
 0.66109026650868441,
 0.65968803694898825,
 0.65135386654868643,
 0.64240398958248246,
 0.64160050881372166,
 0.63830082873615124,
 0.6356668977433978,
 0.63469275405029801,
 0.63406297361561703,
 0.63292569322344749,
 0.63127588607164886,
 0.63093558325029764,
 0.63059342579048394,
 0.62658899688753367,
 0.62576490910889693,
 0.62308718824573828,
 0.62023320827718598,
 0.6201277627677596,
 0.6196053759306217,
 0.61762161659499948,
 0.61614701759925317,
 0.61156939642365271,
 0.61147363459922921,
 0.61072276051139951,
 0.60932749371031025,
 0.60440076333380977,
 0.6022791288

In [347]:
r1 = sorted(result[:,1], reverse = True)
roc_auc_score(y1_test,r1)

0.49692145920796332

In [ ]:
#r1

In [396]:
roc_auc_score(y1_test,result[:,1])

0.70315235055090908

In [61]:
#import lightgbm and xgboost 
import lightgbm as lgb 
import xgboost as xgb 

ModuleNotFoundError: No module named 'lightgbm'